"""v1

Revision ID: 8eadb5b33380
Revises: 
Create Date: 2022-06-20 19:54:43.628439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eadb5b33380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_lista_de_compras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(length=30), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('medida', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_lista_de_compras')
    # ### end Alembic commands ###
